// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgv7FPXi-66y8RwdtjnPiCwopUjRjuh1o',
    appId: '1:1085704871019:web:95d6498d914e937b90a52e',
    messagingSenderId: '1085704871019',
    projectId: 'gesports-9d527',
    authDomain: 'gesports-9d527.firebaseapp.com',
    storageBucket: 'gesports-9d527.firebasestorage.app',
    measurementId: 'G-EEQQ86EVPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8rbiC7_Fj8DoW3pn8m_2JTKgM5S9F2RI',
    appId: '1:1085704871019:android:03800e5db7be79b090a52e',
    messagingSenderId: '1085704871019',
    projectId: 'gesports-9d527',
    storageBucket: 'gesports-9d527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7myjRm2rdhE3hvk9yzrXs-SrQWNIKGL8',
    appId: '1:1085704871019:ios:ce0c6f8ae71aec3690a52e',
    messagingSenderId: '1085704871019',
    projectId: 'gesports-9d527',
    storageBucket: 'gesports-9d527.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7myjRm2rdhE3hvk9yzrXs-SrQWNIKGL8',
    appId: '1:1085704871019:ios:ce0c6f8ae71aec3690a52e',
    messagingSenderId: '1085704871019',
    projectId: 'gesports-9d527',
    storageBucket: 'gesports-9d527.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgv7FPXi-66y8RwdtjnPiCwopUjRjuh1o',
    appId: '1:1085704871019:web:c6b4acadecaa624b90a52e',
    messagingSenderId: '1085704871019',
    projectId: 'gesports-9d527',
    authDomain: 'gesports-9d527.firebaseapp.com',
    storageBucket: 'gesports-9d527.firebasestorage.app',
    measurementId: 'G-7E9SSEE2CK',
  );
}
